<Project>
  <ItemGroup>
    <PackageVersion Include="Expecto" Version="11.0.0" />
    <PackageVersion Include="FSharp.Core" Version="[7.0.200,)" />
    <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="18.6.0" />
    <PackageVersion Include="Microsoft.TestPlatform.ObjectModel" Version="18.6.0" />
  </ItemGroup>
</Project>
